spring:
  application:
    name: luv-backend
  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: "*"
      allowed-headers: "*"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
